# Generated by Django 5.2 on 2025-05-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='descptrion',
            new_name='description',
        ),
    ]
