services:
  backend:
    build: ./backend/djangobnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/djangobnb_backend/:/usr/src/backend/djangobnb_backend/
      - ./media:/usr/src/backend/djangobnb_backend/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  frontend:
    build: ./frontend/djangobnb
    volumes:
      - ./frontend/djangobnb:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_HOST=http://backend:8000

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword 
      - POSTGRES_DB=djangobnb

volumes:
  postgres_data:
